apiVersion: v1
kind: Service
metadata:
  name: four-card-feature-section
  namespace: default
spec:
  selector:
    app: four-card-feature-section-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
